relativeURLs = true
title = "Op. Dr. Gürol Oral"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "taxonomyTerm"]

[author]
name = "Op. Dr. Gürol Oral"

[markup] # needed to add html in .md
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
title = "Kulak Burun Boğaz Hastalıkları Uzmanı"
institution = ""
logo = "img/gurol_workphoto2.jpg"
logo2 = "pdf/chatgpt_edit_logo.png"
Twitter = "emreoral_"
Email = "emre.oral@uni-mannheim.de"