relativeURLs = true
title = "Gürol Oral"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "taxonomyTerm"]

[author]
name = "Op. Dr. Gürol Oral"

[markup] # needed to add html in .md
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
title = "Kulak Burun Boğaz Uzmanı"
institution = "Bodrum, Muğla"
logo = "img/gurol_workphoto2.jpg"
Twitter = "emreoral_"
Email = "emre.oral@uni-mannheim.de"